name = "Raycast"
uuid = "c61cbefd-5868-4483-9364-69221f875375"
authors = ["devansh <devansh@umich.edu> and contributors"]
version = "v0.0.2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
